// 动作菜单数据
let actionList=[
	{
		name:'相册',
		icon:'../../static/images/extends/pic.png',
		event:'pic'
	},
	{
		name:'音频',
		icon:'../../static/images/extends/audio.png',
		event:'audio'
	},{
		name:'视频',
		icon:'../../static/images/extends/video.png',
		event:'video'
	},{
		name:'红包',
		icon:'../../static/images/extends/hongbao.png',
		event:'hongbao'
	},{
		name:'位置',
		icon:'../../static/images/extends/path.png',
		event:'path'
	},{
		name:'电话',
		icon:'../../static/images/extends/phone.png',
		event:'phone'
	},{
		name:'收藏',
		icon:'../../static/images/extends/shoucan.png',
		event:'shoucan'
	},
];
// 聊天数据
let ListData=[
	{
		avatar:'/static/images/demo/demo6.jpg',
		user_id:2,
		create_time:1597143683,
		type:'text',// image video,audio emoticon
		data:'你好，预控中心告诉你，你很棒的哦',
		nickname:'simull',
		iswithdraw:false,
		isdelect:false
	},{
		avatar:'/static/images/demo/demo6.jpg',
		user_id:2,
		create_time:1597143697,
		type:'text',// image video,audio
		data:'你好，预控中心告诉你，你很棒的哦',
		nickname:'simull2',
		iswithdraw:false,
		isdelect:false
	},{
		avatar:'/static/images/demo/demo5.jpg',
		user_id:1,
		create_time:1597143648,
		type:'text',// image video,audio
		data:'你好，预控中心告诉你，你很棒的哦',
		nickname:'simull',
		iswithdraw:false,
		isdelect:false
	},{
		avatar:'/static/images/demo/demo5.jpg',
		user_id:1,
		create_time:1597143648,
		type:'image',// image video,audio
		data:'/static/images/demo/cate_01.png',
		nickname:'simull',
		iswithdraw:false,
		isdelect:false
	},{
		avatar:'/static/images/demo/demo5.jpg',
		user_id:1,
		create_time:1597143648,
		type:'text',// image video,audio
		data:'你好，预控中心告诉你，你很棒的哦',
		nickname:'simull',
		iswithdraw:false,
		isdelect:false
	},{
		avatar:'/static/images/demo/demo6.jpg',
		user_id:2,
		create_time:1597143697,
		type:'text',// image video,audio
		data:'你好，预控中心告诉你，你很棒的哦',
		nickname:'simull2',
		iswithdraw:false,
		isdelect:false
	},
];
//表情
let emoticons = [
	{
		name:'生气1',
		icon:'../../static/images/emoticon/5497/0.gif',
		event:''
	},
	{
		name:'生气2',
		icon:'../../static/images/emoticon/5497/1.gif',
		event:''
	},
	{
		name:'生气3',
		icon:'../../static/images/emoticon/5497/2.gif',
		event:''
	},{
		name:'生气4',
		icon:'../../static/images/emoticon/5497/3.gif',
		event:''
	},{
		name:'生气5',
		icon:'../../static/images/emoticon/5497/4.gif',
		event:''
	},
	{
		name:'生气6',
		icon:'../../static/images/emoticon/5497/5.gif',
		event:''
	},
	{
		name:'生气7',
		icon:'../../static/images/emoticon/5497/6.gif',
		event:''
	},
	{
		name:'生气8',
		icon:'../../static/images/emoticon/5497/7.gif',
		event:''
	},
	{
		name:'生气9',
		icon:'../../static/images/emoticon/5497/8.gif',
		event:''
	}
];

export {
	actionList,
	ListData,
	emoticons
}